source:      .
destination: dist
exclude:     [scss]

relative_permalinks: false

host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000

safe: true
lsi: false
pygments: true